import Image from 'next/image';
import { Gallery } from '~/components/Gallery';
import { Scroller } from '~/components/WorkScroller';

export const metadata = {
  title: 'SDQ ADE',
  description: 'Generated by create next app',
};
export default function Home() {
  return (
    <main id='bg' className='h-full w-full'>
      <div className='h-screen w-full relative'>
        <video
          src='/home.mp4'
          autoPlay
          loop
          muted
          controls={false}
          playsInline
          className='object-cover w-full h-full'
        />
        {/* <div className='absolute inset-0 w-full h-full bg-gradient-to-b from-orange-500/10 to-white/40 backdrop-blur-sm bg-opacity-20 z-[2]'></div> */}
      </div>
      <Scroller word='works' key='works' />
      <Gallery />
    </main>
  );
}
